"use client";

import { useEffect, useState } from "react";
import { hasPermission, type Permission, type UserRole } from "@/lib/permissions";
import { DomainHeader } from "@/app/components/Shared";

type UserRow = { id: number; username: string; name: string; role: UserRole; active: boolean; createdAt: string };

export function UserPanel() {
  const [users, setUsers] = useState<UserRow[]>([]); const [name, setName] = useState(""); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<UserRole>("cashier"); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/users").then(response => response.ok ? response.json() as Promise<UserRow[]> : Promise.reject()).then(setUsers).catch(() => setMessage("ไม่สามารถโหลดข้อมูลผู้ใช้งานได้")); }, []);
  const add = async () => { setMessage(""); const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, username, password, role }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error || "เพิ่มผู้ใช้งานไม่สำเร็จ"); return; } setUsers(current => [result, ...current]); setName(""); setUsername(""); setPassword(""); setMessage("เพิ่มผู้ใช้งานแล้ว"); };
  const toggle = async (user: UserRow) => { const active = !user.active; setUsers(current => current.map(item => item.id === user.id ? { ...item, active } : item)); const response = await fetch(`/api/users?id=${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active }) }); if (!response.ok) setMessage("ไม่สามารถเปลี่ยนสถานะผู้ใช้งานได้"); };
  const remove = async (id: number) => { const response = await fetch(`/api/users?id=${id}`, { method: "DELETE" }); if (!response.ok) { setMessage("ไม่สามารถลบผู้ใช้งานได้"); return; } setUsers(current => current.filter(user => user.id !== id)); };
  return <div className="domain-page"><DomainHeader title="ผู้ใช้งาน" subtitle="สร้างบัญชีและกำหนดบทบาทสำหรับการเข้าใช้งานระบบ" /><div className="domain-form"><input value={name} onChange={e => setName(e.target.value)} placeholder="ชื่อผู้ใช้งาน" /><input value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" /><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="รหัสผ่านอย่างน้อย 6 ตัว" /><select value={role} onChange={e => setRole(e.target.value as UserRole)}><option value="owner">เจ้าของร้าน</option><option value="manager">ผู้จัดการ</option><option value="cashier">แคชเชียร์</option><option value="warehouse">คลังสินค้า</option></select><button className="add-product" disabled={!name.trim() || !username.trim() || password.length < 6} onClick={add}>＋ เพิ่มผู้ใช้งาน</button></div>{message && <p className="adjustment-message">{message}</p>}<div className="domain-list">{users.length === 0 ? <div className="domain-empty"><strong>ยังไม่มีผู้ใช้งานในฐานข้อมูล</strong></div> : users.map(user => <div className="domain-row" key={user.id}><div className="domain-avatar">♙</div><div><b>{user.name}</b><small>{user.username} · {user.role}</small></div><button className={user.active ? "status good" : "status low"} onClick={() => toggle(user)}>{user.active ? "ใช้งาน" : "ปิดใช้งาน"}</button><button className="table-delete" onClick={() => remove(user.id)}>ลบ</button></div>)}</div></div>;
}

export function PermissionPanel() {
  const permissions: Array<[Permission, string]> = [["sell", "ขายหน้าร้าน"], ["view_orders", "ดูรายการขาย"], ["view_reports", "ดูรายงาน"], ["view_inventory", "ดูคลังสินค้า"], ["manage_products", "จัดการสินค้า/เมนู"], ["manage_inventory", "รับเข้าและปรับสต็อก"], ["manage_staff", "จัดการพนักงาน/ผู้ใช้งาน"], ["manage_branches", "จัดการสาขา"], ["manage_settings", "ตั้งค่าร้าน"]];
  const roles: Array<[UserRole, string]> = [["owner", "เจ้าของร้าน"], ["manager", "ผู้จัดการ"], ["cashier", "แคชเชียร์"], ["warehouse", "คลังสินค้า"]];
  return <div className="domain-page"><DomainHeader title="สิทธิ์การเข้าถึง" subtitle="ตรวจสอบขอบเขตการใช้งานของแต่ละบทบาท" /><div className="permission-grid">{roles.map(([role, label]) => <section className="permission-card" key={role}><div><strong>{label}</strong><small>{role}</small></div>{permissions.map(([permission, name]) => <div className="permission-row" key={permission}><span>{name}</span><b className={hasPermission(role, permission) ? "status good" : "status low"}>{hasPermission(role, permission) ? "อนุญาต" : "ไม่อนุญาต"}</b></div>)}</section>)}</div></div>;
}
