"use client";

import { useState } from "react";
import { money } from "@/lib/formatters";
import type { Order } from "@/lib/domain";

export function OrderHistoryPanel({ orders, receiptMode, managementMode, onUpdated }: { orders: Order[]; receiptMode: boolean; managementMode: boolean; onUpdated: (orders: Order[]) => void }) {
  const [actionError, setActionError] = useState(""); const [printOrder, setPrintOrder] = useState<Order | null>(null); const [query, setQuery] = useState("");
  const visibleOrders = orders.filter(order => `${order.id} ${order.customerName || ""} ${order.tableName || ""}`.toLowerCase().includes(query.toLowerCase()));
  const cancel = async (id: string) => { setActionError(""); const response = await fetch(`/api/orders?id=${encodeURIComponent(id)}`, { method: "PATCH" }); if (!response.ok) { const result = await response.json().catch(() => ({})); setActionError(result.error || "ไม่สามารถยกเลิกออร์เดอร์ได้"); return; } const updated = await response.json() as Order; onUpdated(orders.map(order => order.id === id ? updated : order)); };
  const printReceipt = (order: Order) => { setPrintOrder(order); setTimeout(() => window.print(), 50); };
  return <><div className="report-page"><div className="report-heading"><div><h2>{receiptMode ? "ใบเสร็จการขาย" : managementMode ? "จัดการออร์เดอร์" : "รายการขาย"}</h2><span>{receiptMode ? "ดูรายการและพิมพ์ใบเสร็จจากการขาย" : managementMode ? "ตรวจสอบและยกเลิกออร์เดอร์ที่ทำรายการผิดพลาด" : "ประวัติออร์เดอร์ที่บันทึกไว้ในระบบ"}</span></div><div className="report-tools"><input className="report-filter" value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหาออร์เดอร์ ลูกค้า หรือโต๊ะ" /><div className="report-count">{visibleOrders.length}<small>รายการ</small></div></div></div>{actionError && <p className="adjustment-message error-message">{actionError}</p>}<div className="report-table">{visibleOrders.length === 0 ? <div className="management-empty"><div className="management-empty-icon">▤</div><strong>{orders.length === 0 ? "ยังไม่มีรายการขาย" : "ไม่พบออร์เดอร์ที่ค้นหา"}</strong><span>{orders.length === 0 ? "ออร์เดอร์ที่ชำระเงินแล้วจะแสดงที่นี่" : "ลองค้นหาด้วยเลขที่ออร์เดอร์ ชื่อลูกค้า หรือชื่อโต๊ะ"}</span></div> : <table><thead><tr><th>เลขที่รายการ</th><th>วันที่</th><th>โต๊ะ/ลูกค้า</th><th>จำนวนสินค้า</th><th>ยอดรวม</th><th>ชำระผ่าน</th><th>สถานะ</th><th /></tr></thead><tbody>{visibleOrders.map(order => <tr key={order.id}><td><b>{order.id}</b></td><td>{new Date(order.createdAt).toLocaleString("th-TH")}</td><td>{[order.tableName, order.customerName].filter(Boolean).join(" · ") || "ทั่วไป"}</td><td>{order.items.reduce((sum, item) => sum + item.qty, 0)} ชิ้น</td><td><b>{money(order.total)}</b></td><td>{order.paymentMethod === "cash" ? "เงินสด" : order.paymentMethod === "qr" ? "QR" : "บัตร"}</td><td><label className={order.status === "paid" ? "status good" : "status low"}>{order.status === "paid" ? "ชำระแล้ว" : "ยกเลิกแล้ว"}</label></td><td>{receiptMode && <button className="table-action" onClick={() => printReceipt(order)}>พิมพ์ใบเสร็จ</button>}{managementMode && order.status === "paid" && <button className="table-delete" onClick={() => cancel(order.id)}>ยกเลิกออร์เดอร์</button>}</td></tr>)}</tbody></table>}</div></div>{printOrder && <ReceiptView order={printOrder} />}</>;
}

function ReceiptView({ order }: { order: Order }) { return <div className="print-receipt"><h1>ใบเสร็จรับเงิน</h1><p>{order.id}</p><p>{new Date(order.createdAt).toLocaleString("th-TH")}</p>{order.tableName && <p>โต๊ะ: {order.tableName}</p>}{order.customerName && <p>ลูกค้า: {order.customerName}</p>}<hr />{order.items.map(item => <div className="receipt-line" key={item.id}><span>{item.name} × {item.qty}</span><b>{money(item.price * item.qty)}</b></div>)}<hr /><div className="receipt-total"><span>ยอดรวม</span><b>{money(order.total)}</b></div><p>ชำระด้วย: {order.paymentMethod === "cash" ? "เงินสด" : order.paymentMethod === "qr" ? "QR" : "บัตร"}</p></div>; }
