"use client";

import { useState } from "react";
import { money } from "@/lib/formatters";
import type { Order } from "@/lib/domain";

export function ReportsPanel({ orders, bestSellerMode }: { orders: Order[]; bestSellerMode: boolean }) {
  const [range, setRange] = useState<"all" | "today" | "week">("all");
  const [now] = useState(() => Date.now()); const [today] = useState(() => new Date().toDateString());
  const visibleOrders = orders.filter(order => order.status === "paid").filter(order => range === "all" || (range === "today" ? now - new Date(order.createdAt).getTime() < 86400000 && new Date(order.createdAt).toDateString() === today : now - new Date(order.createdAt).getTime() < 7 * 86400000));
  const total = visibleOrders.reduce((sum, order) => sum + order.total, 0);
  const quantity = visibleOrders.reduce((sum, order) => sum + order.items.reduce((itemSum, item) => itemSum + item.qty, 0), 0);
  const best = new Map<number, { name: string; qty: number; total: number }>();
  visibleOrders.forEach(order => order.items.forEach(item => { const current = best.get(item.id) ?? { name: item.name, qty: 0, total: 0 }; best.set(item.id, { name: current.name, qty: current.qty + item.qty, total: current.total + item.price * item.qty }); }));
  const bestRows = [...best.values()].sort((a, b) => b.qty - a.qty);
  const exportCsv = () => { const rows = [["order_id", "created_at", "table", "customer", "payment_method", "status", "total", "items"], ...visibleOrders.map(order => [order.id, order.createdAt, order.tableName || "", order.customerName || "ทั่วไป", order.paymentMethod, order.status, String(order.total), String(order.items.reduce((sum, item) => sum + item.qty, 0))])]; const csv = rows.map(row => row.map(value => `"${value.replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `shoppos-sales-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="report-page"><div className="report-heading"><div><h2>{bestSellerMode ? "สินค้าขายดี" : "สรุปยอดขาย"}</h2><span>{bestSellerMode ? "จัดอันดับจากจำนวนสินค้าที่ขายได้" : "ภาพรวมจากรายการขายที่ชำระเงินแล้ว"}</span></div><div className="report-tools"><select value={range} onChange={e => setRange(e.target.value as typeof range)}><option value="all">ทุกช่วงเวลา</option><option value="today">วันนี้</option><option value="week">7 วันที่ผ่านมา</option></select><button className="table-action" onClick={exportCsv}>ส่งออก CSV</button></div></div><div className="report-stats"><div><span>ยอดขายรวม</span><strong>{money(total)}</strong></div><div><span>ออร์เดอร์</span><strong>{visibleOrders.length}</strong></div><div><span>สินค้าที่ขาย</span><strong>{quantity}</strong></div></div>{bestSellerMode ? <div className="report-table">{bestRows.length === 0 ? <div className="management-empty"><div className="management-empty-icon">▥</div><strong>ยังไม่มีข้อมูลสินค้าขายดี</strong><span>ข้อมูลจะแสดงหลังมีการชำระเงิน</span></div> : <table><thead><tr><th>อันดับ</th><th>สินค้า</th><th>จำนวนที่ขาย</th><th>ยอดขาย</th></tr></thead><tbody>{bestRows.map((row, index) => <tr key={row.name}><td>{index + 1}</td><td><b>{row.name}</b></td><td>{row.qty} ชิ้น</td><td>{money(row.total)}</td></tr>)}</tbody></table>}</div> : <div className="report-table"><table><thead><tr><th>วันที่</th><th>ออร์เดอร์</th><th>ยอดขาย</th><th>สถานะ</th></tr></thead><tbody>{visibleOrders.length === 0 ? <tr><td colSpan={4} className="empty-table">ยังไม่มีข้อมูลยอดขาย</td></tr> : visibleOrders.map(order => <tr key={order.id}><td>{new Date(order.createdAt).toLocaleDateString("th-TH")}</td><td>{order.id}</td><td>{money(order.total)}</td><td><label className="status good">ชำระแล้ว</label></td></tr>)}</tbody></table></div>}</div>;
}
