"use client";

import { useEffect, useState } from "react";
import { patchResource, postResource, type ApiResource } from "@/lib/client-resources";
import { Toggle } from "@/app/components/Shared";

function detailsOf(value: string) { try { return JSON.parse(value) as Record<string, unknown>; } catch { return {}; } }

export function SettingsPanel({ onBack }: { onBack: () => void }) {
  const [saved, setSaved] = useState(false); const [error, setError] = useState(""); const [recordId, setRecordId] = useState<number | null>(null); const [shopName, setShopName] = useState(""); const [branchName, setBranchName] = useState(""); const [tax, setTax] = useState("ไม่รวมภาษี"); const [receipt, setReceipt] = useState(true); const [sound, setSound] = useState(true);
  useEffect(() => { fetch("/api/management/settings").then(response => response.ok ? response.json() as Promise<ApiResource[]> : Promise.reject()).then(rows => { const row = rows[0]; if (!row) return; const details = detailsOf(row.details); setRecordId(row.id); setShopName(String(details.shopName ?? "")); setBranchName(String(details.branchName ?? "")); setTax(String(details.tax ?? "ไม่รวมภาษี")); setReceipt(details.receipt !== false); setSound(details.sound !== false); }).catch(() => undefined); }, []);
  const save = async () => { setError(""); const details = JSON.stringify({ shopName, branchName, tax, receipt, sound }); try { if (!recordId) { const row = await postResource("settings", { name: "การตั้งค่าร้าน", details }); if (!row) { setError("ไม่สามารถบันทึกการตั้งค่าได้"); return; } setRecordId(row.id); } else { const response = await patchResource("settings", recordId, { name: "การตั้งค่าร้าน", details }); if (!response.ok) { setError("ไม่สามารถบันทึกการตั้งค่าได้"); return; } } setSaved(true); setTimeout(() => setSaved(false), 2200); } catch { setError("ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้"); } };
  return <div className="settings-panel"><div className="settings-head"><div><button className="back-link" onClick={onBack}>← กลับไประบบจัดการร้านค้า</button><h2>ตั้งค่าระบบ</h2><span>กำหนดค่าการทำงานของร้านค้าและหน้าขายหน้าร้าน</span></div><button className="save-settings" onClick={save}>{saved ? "บันทึกแล้ว ✓" : "บันทึกการตั้งค่า"}</button></div>{error && <p className="adjustment-message error-message">{error}</p>}<div className="settings-sections"><section className="settings-section"><div className="settings-section-title"><span>⚙</span><div><strong>ตั้งค่าร้านค้า</strong><span>ข้อมูลพื้นฐานที่ใช้แสดงในระบบ</span></div></div><label>ชื่อร้าน<input value={shopName} onChange={e => setShopName(e.target.value)} placeholder="กรอกชื่อร้านค้า" /></label><label>สาขาหลัก<input value={branchName} onChange={e => setBranchName(e.target.value)} placeholder="กรอกชื่อสาขา" /></label></section><section className="settings-section"><div className="settings-section-title"><span>▤</span><div><strong>การขายและใบเสร็จ</strong><span>ตั้งค่ารูปแบบการคิดเงิน</span></div></div><label>รูปแบบภาษี<select value={tax} onChange={e => setTax(e.target.value)}><option>ไม่รวมภาษี</option><option>รวมภาษีแล้ว</option></select></label><Toggle label="ออกใบเสร็จอัตโนมัติ" value={receipt} onChange={() => setReceipt(!receipt)} /><Toggle label="เสียงแจ้งเตือนเมื่อชำระเงิน" value={sound} onChange={() => setSound(!sound)} /></section></div></div>;
}

export function SystemPanel({ onSelect }: { onSelect: (title: string) => void }) {
  const cards = [["☰", "ออกแบบเมนู", "จัดหมวดหมู่และรายการอาหารหรือสินค้า"], ["▤", "จัดการโต๊ะ", "ตั้งค่าโซนโต๊ะและสถานะการใช้งาน"], ["▧", "จัดการออร์เดอร์", "ติดตามและจัดการออร์เดอร์ของร้าน"], ["♙", "จัดการพนักงาน", "เพิ่มพนักงานและกำหนดสิทธิ์การใช้งาน"], ["⌂", "จัดการสาขา", "เพิ่มและดูแลข้อมูลสาขาของร้าน"], ["♧", "ลูกค้า", "จัดการข้อมูลลูกค้าและประวัติการซื้อ"], ["♙", "ผู้ใช้งาน", "เพิ่มและจัดการบัญชีผู้ใช้งาน"], ["◇", "สิทธิ์การเข้าถึง", "กำหนดสิทธิ์สำหรับแต่ละบทบาท"], ["⚙", "ตั้งค่าร้าน", "ข้อมูลร้าน ช่องทางชำระเงิน และใบเสร็จ"]];
  return <div className="system-panel"><div className="system-heading"><div><h2>ระบบจัดการร้านค้า</h2><span>จัดการการตั้งค่าและผู้ใช้งานของร้าน</span></div></div><div className="system-grid">{cards.map(([icon, title, description]) => <button className="system-card" key={title} onClick={() => onSelect(title)}><div className="system-icon">{icon}</div><div><strong>{title}</strong><span>{description}</span></div><b>›</b></button>)}</div></div>;
}
